version: '3'
services:


  wg-easy:
    build:
      context: .
      dockerfile: dev-wg/Dockerfile  
    deploy:
      resources:
        limits:
          cpus: '${CPU_limits}'       # กำหนดการใช้ CPU
          memory: '${RAM_limits}'     # กำหนดการใช้ RAM (เช่น 512 MB)
        # reservations:
        #   memory: '256M'     # กำหนด RAM ที่ container ควรจะมีอย่างน้อย (256 MB)
    # image: weejewel/wg-easy
    container_name: WG-GUI
    # restart: unless-stopped
    ports:
      - "51000:51820/udp"
      - "51000:51821/tcp"
    volumes:
      - ~/.wg-easy:/etc/wireguard
      - ./var-wg:/var
      - ./performance.py:/home/performance.py
      # - ./wireguard-profile:/etc/wireguard
      


    environment:
      # - WG_HOST=localhost
      - WG_HOST=172.16.100.10
      - PASSWORD=admin
      - WG_PORT=51000
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.0.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 1.1.0.0
      - WG_ALLOWED_IPS=0.0.0.0/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:    
      nat-server:
        ipv4_address: 192.168.100.254    
      vpn-net:
        ipv4_address: 172.16.100.10            
   
# docker exec -it WG-GUI bash

  iperf-server:
    build:
      context: .
      dockerfile: dev-iperf/Dockerfile  
    container_name: iperf-server
    ports:
      - "8082:80"
      - "5201:5201"
    networks:      
      nat-server:
        ipv4_address: 192.168.100.100   
# docker exec -it iperf-server bash
# iperf3 -c localhost -t 10

# -------------------------------------------------------------------------------

  client:
    build:
      context: .
      dockerfile: dev-client/Dockerfile  
    cap_add:
      - NET_ADMIN
      - SYS_MODULE      
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1            
    container_name: client
    ports:
      - "8083:80"
    networks:
      vpn-net:
        ipv4_address: 172.16.100.20
    volumes:
      - ./wireguard-profile:/etc/wireguard 
      - /lib/modules:/lib/modules



# docker exec -it client bash

# การเปิดใช้งานเมื่อบูทเครื่อง
# sudo systemctl enable wg-quick@wg0


# ---------------------------------------------------------------------------------

  # wireguard-client:
  #   build:
  #     context: .
  #     dockerfile: dev-WG-Client/Dockerfile    
  #   # image: linuxserver/wireguard:1.0.20210914
  #   container_name: wireguard-client
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Rome
  #   volumes:
  #     - ./config/opt/wireguard-server/config:/config
  #     - /lib/modules:/lib/modules
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped
  #   networks:
  #     vpn-net:
  #       ipv4_address: 172.16.100.20    

# -----------------------------------------------------------------------------------
networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24      
        
  nat-server:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  # nat-client:
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 10.0.0.0/24        


# docker-compose up -d



