FROM debian:bookworm-backports
RUN apt-get update && apt-get install -y apache2
RUN apt install net-tools
RUN apt install iputils-ping -y
RUN apt install iperf3 -y


COPY dev-client/start.sh /
RUN chmod +x /start.sh
# # for cpu data
# RUN apt-get install sysstat -y
# # for ram data 
# RUN apt-get install procps -y 

RUN rm /var/www/html/index.html
RUN  touch /var/www/html/"This is Iperf-Server"
ENV TZ=Asia/Bangkok



RUN apt install wireguard -y
RUN apt install iproute2 -y
EXPOSE 80
# CMD [ "apache2ctl","-D","FOREGROUND" ]
CMD ["/bin/bash","-c","/start.sh"]



# install WG-client





