FROM weejewel/wg-easy:latest
RUN apk update
RUN apk add python3
RUN apk add py3-pip

# RUN python3 --version && pip3 --version

RUN ln -sf python3 /usr/bin/python

# RUN mkdir /home/vpn
COPY dev-wg/performance.py /home
RUN chmod +x /home/performance.py

ENV TZ=Asia/Bangkok







